#!/usr/bin/env python3
"""check_numbers.py - does every measured number in a note appear in its reference script's output?

The method's binding rule (CLAUDE.md, NOTE_TEMPLATE.md): numbers in prose must match code output
verbatim. Until now nothing checked it. This does, mechanically:

  1. For each scripts/noteNNN_reference.py, find the note that names that script (research_notes/*.md).
  2. Run the script (same arguments as CI) and capture its output.
  3. Take every *measurement-like* number in the note: a decimal with at least 3 significant digits
     (0.984, 1.6398, 0.925014, 4.847818e-05), or a ratio/percent written the same way. Integers, dates,
     note numbers and 1-2 digit decimals are skipped: they are mostly parameters and prose.
  4. A number is FOUND if the output contains it as a token. It is also found if the output prints the
     same value to more places (the note may round: 0.9250 in prose, 0.925014 in output).

A NOT FOUND number is a lead for a human, not a verdict: it may be a quoted parameter, a number from
another note, or a hand-typed value that drifted from the code. The report lists each one with its line.

  python scripts/check_numbers.py [--only 044 ...] [--plant]    (--plant: anti-vacuity self-test)
Exit: 0 report written | 1 the self-test failed | 2 could not run
Stdlib only.
"""
import os, re, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ARGS = {"060": ["--selftest"], "061": ["."]}  # the same arguments CI passes
NUM = re.compile(r"(?<![\w.])[-+]?(?:\d+\.\d+(?:[eE][-+]?\d+)?|\d+(?:[eE][-+]?\d+))(?![\w.])")


def sig_digits(tok):
    mant = tok.lstrip("+-").split("e")[0].split("E")[0].replace(".", "").lstrip("0")
    return len(mant)


def measured(tok):
    return ("." in tok or "e" in tok.lower()) and sig_digits(tok) >= 3


def found(tok, out_tokens, out_values):
    if tok in out_tokens or tok.lstrip("+") in out_tokens:
        return True
    try:
        v = float(tok)
    except ValueError:
        return False
    places = len(tok.split("e")[0].split("E")[0].split(".")[1]) if "." in tok else 0
    # the output printed the same value to more places, and the note rounded it
    return any(round(o, places) == round(v, places) and abs(o - v) <= 0.5 * 10 ** -places + 1e-12
               for o in out_values)


def note_for(num):
    hits = []
    for name in sorted(os.listdir(os.path.join(ROOT, "research_notes"))):
        if name.endswith(".md"):
            text = open(os.path.join(ROOT, "research_notes", name), encoding="utf-8").read()
            if f"note{num}_reference" in text and (name.startswith(f"note{num}") or name.startswith(num)):
                hits.append(name)
    return hits[0] if len(hits) == 1 else None


def check(num, note_text, output):
    out_tokens = set(NUM.findall(output))
    out_values = []
    for t in out_tokens:
        try:
            out_values.append(float(t))
        except ValueError:
            pass
    rows = []
    in_fence = False
    for i, line in enumerate(note_text.splitlines(), 1):
        if line.strip().startswith("```"):
            in_fence = not in_fence
        for tok in NUM.findall(line):
            if measured(tok):
                rows.append((i, tok, found(tok, out_tokens, out_values), in_fence))
    return rows


def run_script(num):
    path = os.path.join(ROOT, "scripts", f"note{num}_reference.py")
    p = subprocess.run([sys.executable, path, *ARGS.get(num, [])], cwd=ROOT, capture_output=True, text=True,
                       timeout=900)
    return p.returncode, p.stdout + p.stderr


def self_test():
    """Anti-vacuity: a note that quotes its output passes; the same note with one number changed fails."""
    out = "benefit fell 5472x\nAUC 0.984217\nratio 1.6398 -> 0.00030\n"
    good = "The AUC was 0.984 and the benefit 1.6398, falling to 0.00030."
    bad = good.replace("1.6398", "1.6498")
    g = [r for r in check("x", good, out) if not r[2]]
    b = [r for r in check("x", bad, out) if not r[2]]
    ok = (g == [] and [t for _, t, _, _ in b] == ["1.6498"])
    print(f"self-test: honest note {len(g)} not found; planted wrong number flagged: {[t for _, t, _, _ in b]}"
          f" -> {'PASS' if ok else 'FAIL'}")
    return ok


def main():
    argv = sys.argv[1:]
    if "--plant" in argv:
        sys.exit(0 if self_test() else 1)
    only = [a for a in argv if a.isdigit()]
    if not self_test():
        sys.exit(1)
    nums = sorted(f[4:7] for f in os.listdir(os.path.join(ROOT, "scripts"))
                  if re.fullmatch(r"note\d{3}_reference\.py", f))
    total_n = total_f = 0
    report = ["# Number check: prose against reference-script output", "",
              "Generated by `python scripts/check_numbers.py`. NOT FOUND is a lead, not a verdict (see the script).", "",
              "| note | file | script exit | measured numbers | found | not found |", "|---|---|---|---|---|---|"]
    details = []
    for num in nums:
        if only and num not in only:
            continue
        name = note_for(num)
        if name is None:
            report.append(f"| {num} | (no unique note names note{num}_reference) | - | - | - | - |")
            continue
        text = open(os.path.join(ROOT, "research_notes", name), encoding="utf-8").read()
        code, out = run_script(num)
        rows = check(num, text, out)
        nf = [r for r in rows if not r[2]]
        total_n += len(rows)
        total_f += len(rows) - len(nf)
        report.append(f"| {num} | {name} | {code} | {len(rows)} | {len(rows) - len(nf)} | {len(nf)} |")
        print(f"note{num}: {name}: exit {code}, {len(rows)} measured numbers, {len(nf)} not found in the output")
        if nf:
            details.append(f"\n## {name}\n")
            details += [f"- line {i}: `{t}`{' (in a code block)' if fence else ''}" for i, t, _, fence in nf]
    report.append(f"\n**Total:** {total_f} of {total_n} measured numbers appear in their script's output.")
    with open(os.path.join(ROOT, "results", "NUMBER_CHECK.md"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(report + details) + "\n")
    print(f"TOTAL {total_f}/{total_n} found; report: results/NUMBER_CHECK.md")


if __name__ == "__main__":
    main()
