"""Self-regenerating notes index for Principia Artificialis — v3.
v3 (2026-09-27): a Tier column maps each note's own status string onto the README's documented tiers
(Verified / Draft / Speculative), by fixed rules below, without editing any note; strings no rule
covers are shown as "Unmapped" and counted, so the drift is visible and each one is a five-minute PR.
Also: the ⚠ mark is no longer appended twice when a status already carries one.
v2 fix: v1 globbed only note*.md and silently excluded the entire NNN_ series
(44 files). The index now covers BOTH series and visibly flags number
collisions instead of hiding them. The notes are the source of truth.
Run from repo root:  python scripts/make_index.py
"""
import re, glob, os, datetime
from collections import Counter

paths = sorted(set(glob.glob("research_notes/note[0-9][0-9][0-9]_*.md")
                   + glob.glob("research_notes/[0-9][0-9][0-9]_*.md")
                   + glob.glob("notes/[0-9][0-9][0-9]_*.md")))

rows = []
for path in paths:
    txt = open(path, encoding="utf-8", errors="replace").read()
    base = os.path.basename(path)
    mnum = re.match(r"(?:note)?(\d{3})_", base)
    num = mnum.group(1) if mnum else "999"
    m = re.search(r"^#\s*(?:Note\s*)?#?\d*\s*[—–:-]?\s*(.+)$", txt, re.M)
    title = m.group(1).strip() if m and m.group(1).strip() else base.replace(".md", "")
    def grab(label):
        g = re.search(rf"\*\*{label}:?\*\*:?\s*([^\n|]+)", txt)
        if not g:
            g = re.search(rf"^{label}:\s*([^\n]+)", txt, re.M | re.I)
        return re.sub(r"\s+", " ", g.group(1)).strip() if g else "—"
    status = grab("Status")
    status_short = re.split(r"[;(]", status)[0].strip()
    if ("REFUT" in status.upper() or "FAILED" in status.upper()) and "⚠" not in status_short:
        status_short += " ⚠ refutation kept"
    author = grab("Author") if grab("Author") != "—" else grab("Authors")
    author_short = re.split(r"[—–,;(]", author)[0].strip() or "—"
    rows.append((int(num), num, f"[{title}]({path})", status_short, author_short, path))

def tier(status):
    """The README's documented tiers. Rules are ordered; the first that matches decides."""
    s = status.lower()
    if "does not reproduce" in s or "instrument lost" in s:
        return "Draft"            # code exists but does not print the claimed numbers
    if "verified reference code" in s or s.startswith("verified"):
        return "Verified"         # README: reference code prints every number claimed
    if "speculat" in s or "pure ai" in s or "freestyle" in s:
        return "Speculative"      # includes the AI-conception labels: argued, no code
    if s.startswith("draft"):
        return "Draft"
    return "Unmapped"


rows.sort()
dupes = {n for n, c in Counter(r[0] for r in rows).items() if c > 1}
today = datetime.date.today().isoformat()
out = ["# Notes Index", "",
       f"*Auto-generated by `scripts/make_index.py` (v3) on {today} — "
       f"do not edit by hand; edit the notes and re-run.*", "",
       f"**{len(rows)} notes indexed across both series "
       f"({len(dupes)} numbers claimed by multiple notes — marked ⚡; "
       f"collisions are displayed, not hidden).** "
       f"⚠ marks a registered claim that failed and was kept.", "",
       ]
tiers = Counter(tier(r[3]) for r in rows)
unmapped = sorted({r[3] for r in rows if tier(r[3]) == "Unmapped"})
out += ["**By tier** (mapped from each note's own status by `tier()` in this script; no note edited): "
        + ", ".join(f"{t} {tiers.get(t, 0)}" for t in ("Verified", "Draft", "Speculative", "Unmapped"))
        + f". Distinct status strings in use: {len({r[3] for r in rows})}."
        + (" Unmapped strings (map one in its note for a five-minute PR): "
           + "; ".join(f"`{u}`" for u in unmapped) if unmapped else ""), "",
        "| # | Note | Status (as written) | Tier | Author |", "|---|---|---|---|---|"]
for n, num, link, status, author, _ in rows:
    mark = " ⚡" if n in dupes else ""
    out.append(f"| #{num}{mark} | {link} | {status} | {tier(status)} | {author} |")
open("NOTES_INDEX.md", "w", encoding="utf-8").write("\n".join(out) + "\n")
print("tiers: " + ", ".join(f"{t} {c}" for t, c in sorted(tiers.items())))
print(f"NOTES_INDEX.md written: {len(rows)} notes, {len(dupes)} collided numbers: "
      + ", ".join(f"#{d:03d}" for d in sorted(dupes)))
