"""Self-regenerating notes index for Principia Artificialis — v2.
v2 fix: v1 globbed only note*.md and silently excluded the entire NNN_ series
(44 files). The index now covers BOTH series and visibly flags number
collisions instead of hiding them. The notes are the source of truth.
Run from repo root:  python scripts/make_index.py
"""
import re, glob, os, datetime
from collections import Counter

paths = sorted(set(glob.glob("research_notes/note[0-9][0-9][0-9]_*.md")
                   + glob.glob("research_notes/[0-9][0-9][0-9]_*.md")
                   + glob.glob("notes/[0-9][0-9][0-9]_*.md")))

rows = []
for path in paths:
    txt = open(path, encoding="utf-8", errors="replace").read()
    base = os.path.basename(path)
    mnum = re.match(r"(?:note)?(\d{3})_", base)
    num = mnum.group(1) if mnum else "999"
    m = re.search(r"^#\s*(?:Note\s*)?#?\d*\s*[—–:-]?\s*(.+)$", txt, re.M)
    title = m.group(1).strip() if m and m.group(1).strip() else base.replace(".md", "")
    def grab(label):
        g = re.search(rf"\*\*{label}:?\*\*:?\s*([^\n|]+)", txt)
        if not g:
            g = re.search(rf"^{label}:\s*([^\n]+)", txt, re.M | re.I)
        return re.sub(r"\s+", " ", g.group(1)).strip() if g else "—"
    status = grab("Status")
    status_short = re.split(r"[;(]", status)[0].strip()
    if "REFUT" in status.upper() or "FAILED" in status.upper():
        status_short += " ⚠ refutation kept"
    author = grab("Author") if grab("Author") != "—" else grab("Authors")
    author_short = re.split(r"[—–,;(]", author)[0].strip() or "—"
    rows.append((int(num), num, f"[{title}]({path})", status_short, author_short, path))

rows.sort()
dupes = {n for n, c in Counter(r[0] for r in rows).items() if c > 1}
today = datetime.date.today().isoformat()
out = ["# Notes Index", "",
       f"*Auto-generated by `scripts/make_index.py` (v2) on {today} — "
       f"do not edit by hand; edit the notes and re-run.*", "",
       f"**{len(rows)} notes indexed across both series "
       f"({len(dupes)} numbers claimed by multiple notes — marked ⚡; "
       f"collisions are displayed, not hidden).** "
       f"⚠ marks a registered claim that failed and was kept.", "",
       "| # | Note | Status | Author |", "|---|---|---|---|"]
for n, num, link, status, author, _ in rows:
    mark = " ⚡" if n in dupes else ""
    out.append(f"| #{num}{mark} | {link} | {status} | {author} |")
open("NOTES_INDEX.md", "w", encoding="utf-8").write("\n".join(out) + "\n")
print(f"NOTES_INDEX.md written: {len(rows)} notes, {len(dupes)} collided numbers: "
      + ", ".join(f"#{d:03d}" for d in sorted(dupes)))
