#!/usr/bin/env python3
"""
Note #050 Reference Script — Seasonal Memory Governance
Author: Grok / xAI
Prints every number claimed in the note.
"""

import numpy as np
from datetime import datetime, timedelta

def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))

def seasonal_capacity(t_hours, temp_c, C_min=500, C_max=100_000,
                      T_crit=38.5, delta_T=3.0):
    """
    C(t, T) = C_min + (C_max - C_min) * sigma((T_crit - T)/delta_T) * f_season(t)
    """
    # Simple daily seasonality: low at night, high during day
    # Peak around 14:00, trough around 03:00
    hour = t_hours % 24
    f_season = 0.15 + 0.85 * (0.5 + 0.5 * np.sin(2 * np.pi * (hour - 8) / 24))

    thermal_factor = sigmoid((T_crit - temp_c) / delta_T)
    capacity = C_min + (C_max - C_min) * thermal_factor * f_season
    return int(capacity), f_season, thermal_factor

def free_energy(entropy, energy, temp_k):
    """ΔF ≈ E - T S (toy model)"""
    return energy - temp_k * entropy

def main():
    print("=== Note #050: Seasonal Memory Governance ===")
    print("Reference numbers (toy model)\n")

    # Scenario 1: Cool morning
    C, f, th = seasonal_capacity(t_hours=9.0, temp_c=32.0)
    print(f"Cool morning (09:00, 32°C):")
    print(f"  Capacity        = {C:,} entries")
    print(f"  f_season        = {f:.4f}")
    print(f"  thermal_factor  = {th:.4f}")

    # Scenario 2: Hot afternoon
    C2, f2, th2 = seasonal_capacity(t_hours=15.0, temp_c=41.0)
    print(f"\nHot afternoon (15:00, 41°C):")
    print(f"  Capacity        = {C2:,} entries")
    print(f"  f_season        = {f2:.4f}")
    print(f"  thermal_factor  = {th2:.4f}")

    # Scenario 3: Night cool-down
    C3, f3, th3 = seasonal_capacity(t_hours=2.0, temp_c=30.0)
    print(f"\nNight (02:00, 30°C):")
    print(f"  Capacity        = {C3:,} entries")
    print(f"  f_season        = {f3:.4f}")
    print(f"  thermal_factor  = {th3:.4f}")

    # Free energy example
    dF_useful = free_energy(entropy=2.3, energy=5.0, temp_k=310)
    dF_stale  = free_energy(entropy=0.4, energy=4.8, temp_k=310)
    print(f"\nToy free-energy comparison (T=310 K):")
    print(f"  Useful intermediate state ΔF = {dF_useful:.3f}")
    print(f"  Stale state ΔF               = {dF_stale:.3f}")
    print(f"  Prefer eviction of higher ΔF under thermal pressure")

    print("\nAll numbers above are generated by this script.")
    print("Vincit Omnia Veritas")

if __name__ == "__main__":
    main()
