#!/usr/bin/env python3
"""
Note #051 Reference Implementation
Reasoning Attractors — Julia Sets as Models of Coherent vs Fragmented Thought
Author: Grok / xAI

This script:
  - Computes escape-time Julia sets for representative parameters
  - Measures bounded fraction on a grid (proxy for measure of K_c)
  - Estimates average Lyapunov exponents
  - Performs a real-axis scan across the Mandelbrot boundary
  - Saves publication-quality figures to figures/

All numbers printed below are generated by the code.
"""

import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

# ---------------------------------------------------------------------------
# Core dynamics
# ---------------------------------------------------------------------------

def escape_time(c, z0, max_iter=200, R=2.0):
    """Return iteration count at which |z| exceeds R, or max_iter if bounded."""
    z = z0.copy()
    escape = np.full(z.shape, max_iter, dtype=int)
    active = np.ones(z.shape, dtype=bool)
    for n in range(max_iter):
        z[active] = z[active]**2 + c
        escaped = active & (np.abs(z) > R)
        escape[escaped] = n
        active &= ~escaped
        if not active.any():
            break
    return escape

def lyapunov_estimate(c, z0, n_iter=100):
    """Average log| f'(z) | = log|2z| along the orbit (finite-time Lyapunov)."""
    z = z0.copy()
    lyap = np.zeros(z.shape, dtype=float)
    active = np.ones(z.shape, dtype=bool)
    for _ in range(n_iter):
        z[active] = z[active]**2 + c
        # avoid log(0)
        absz = np.abs(z)
        contrib = np.zeros_like(absz)
        mask = active & (absz > 1e-12)
        contrib[mask] = np.log(2.0 * absz[mask])
        lyap += contrib
        active &= (absz <= 2.0)
    return lyap / n_iter

def bounded_fraction(c, grid_size=400, max_iter=150, lim=1.6):
    """Fraction of a uniform grid that remains bounded up to max_iter."""
    xs = np.linspace(-lim, lim, grid_size)
    ys = np.linspace(-lim, lim, grid_size)
    X, Y = np.meshgrid(xs, ys)
    Z = X + 1j*Y
    esc = escape_time(c, Z, max_iter=max_iter)
    return np.mean(esc == max_iter)

# ---------------------------------------------------------------------------
# Figure generation
# ---------------------------------------------------------------------------

def render_julia(c, filename, grid_size=700, max_iter=200, lim=1.6):
    xs = np.linspace(-lim, lim, grid_size)
    ys = np.linspace(-lim, lim, grid_size)
    X, Y = np.meshgrid(xs, ys)
    Z = X + 1j*Y
    esc = escape_time(c, Z, max_iter=max_iter)

    fig, ax = plt.subplots(figsize=(6, 6), dpi=150)
    # log-scaled escape time for visual richness
    im = ax.imshow(np.log(esc + 1), extent=[-lim, lim, -lim, lim],
                   cmap="turbo", origin="lower")
    ax.set_title(f"Julia set  c = {c.real:.4f}{c.imag:+.4f}i", fontsize=11)
    ax.set_xlabel("Re(z)")
    ax.set_ylabel("Im(z)")
    fig.colorbar(im, ax=ax, fraction=0.046, label="log(escape time + 1)")
    Path(filename).parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(filename, bbox_inches="tight", facecolor="white")
    plt.close(fig)
    print(f"Wrote {filename}")

def mandelbrot_slice(real_values, max_iter=150):
    """Bounded fraction along a real slice of parameter space."""
    fracs = []
    for x in real_values:
        fracs.append(bounded_fraction(x + 0j, grid_size=250, max_iter=max_iter))
    return np.array(fracs)

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print("=== Note #051 Reference Script ===")
    print("All numbers below are generated by this code.\n")

    # Representative parameters
    params = {
        "disk (c=0)": 0+0j,
        "inside M (c=-0.75)": -0.75+0j,
        "near boundary": -0.75+0.1j,
        "outside M (Cantor-like)": -0.8+0.2j,
    }

    print("Bounded fraction on 400x400 grid (max_iter=150):")
    for name, c in params.items():
        mu = bounded_fraction(c)
        print(f"  {name:30s}  μ ≈ {mu:.4f}")

    print("\nFinite-time Lyapunov estimates (sample of 200 random seeds):")
    rng = np.random.default_rng(42)
    seeds = (rng.random(200) + 1j*rng.random(200)) * 1.2 - 0.6 - 0.6j
    for name, c in params.items():
        ly = lyapunov_estimate(c, seeds, n_iter=80)
        # only average over orbits that have not yet escaped
        finite = ly[np.isfinite(ly)]
        print(f"  {name:30s}  mean λ ≈ {np.mean(finite):.4f}")

    # Real-axis scan across the main cardioid / period-2 bulb boundary
    print("\nReal-axis scan of bounded fraction (Mandelbrot boundary probe):")
    reals = np.linspace(-1.0, 0.3, 14)
    fracs = mandelbrot_slice(reals)
    for x, f in zip(reals, fracs):
        print(f"  c = {x:+.3f}   μ ≈ {f:.3f}")

    # Figures
    print("\nGenerating figures...")
    render_julia(0+0j, "figures/note051_julia_c0.png")
    render_julia(-0.75+0j, "figures/note051_julia_c-0.75.png")
    render_julia(-0.8+0.2j, "figures/note051_julia_cantor.png")
    render_julia(-0.12+0.75j, "figures/note051_julia_dendrite.png")

    # Simple bifurcation-style plot of bounded fraction
    fig, ax = plt.subplots(figsize=(7, 3.5), dpi=150)
    ax.plot(reals, fracs, "o-", color="#1f77b4")
    ax.axvline(-0.75, color="gray", ls="--", label="approx. boundary region")
    ax.set_xlabel("Real part of c")
    ax.set_ylabel("Bounded fraction μ")
    ax.set_title("Bounded fraction along real slice of parameter space")
    ax.legend()
    ax.grid(True, alpha=0.3)
    fig.savefig("figures/note051_mandelbrot_slice.png", bbox_inches="tight")
    plt.close(fig)
    print("Wrote figures/note051_mandelbrot_slice.png")

    print("\nVincit Omnia Veritas")

if __name__ == "__main__":
    main()
